package com.compomics.searchgui_xl.view;

import com.compomics.searchgui_xl.controller.MainFrameController;
import com.compomics.searchgui_xl.model.ConfigHolder;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
/**
 *
 * @author Genet
 */
public class MainGUI extends javax.swing.JFrame {

    /**
     * Creates new form MainGUI
     */
    MainFrameController frmController;
    public MainGUI(MainFrameController frmControl) {

        frmController=frmControl;
        initComponents();        
         
       
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlUserInput = new javax.swing.JPanel();
        lblDatabasepath = new javax.swing.JLabel();
        lblSpectrumPath = new javax.swing.JLabel();
        lblOutputFolder = new javax.swing.JLabel();
        txtDatabasePath = new javax.swing.JTextField();
        txtSpectrumPath = new javax.swing.JTextField();
        txtOutPutFolder = new javax.swing.JTextField();
        btnDatabasePath = new javax.swing.JButton();
        btnSpectrumPath = new javax.swing.JButton();
        btnOutPutFolder = new javax.swing.JButton();
        lblCrossLinker = new javax.swing.JLabel();
        cmbCrossLinker = new javax.swing.JComboBox<>();
        btnAdvancedSettings = new javax.swing.JButton();
        pnlTools = new javax.swing.JPanel();
        chkXilmass = new javax.swing.JCheckBox();
        chkKojak = new javax.swing.JCheckBox();
        btnRun = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuFile1 = new javax.swing.JMenu();
        mnuFile = new javax.swing.JMenuItem();
        mnuSave = new javax.swing.JMenuItem();
        mnuExit = new javax.swing.JMenuItem();
        mnuEdit = new javax.swing.JMenu();
        mnuEditComnSetting = new javax.swing.JMenuItem();
        mnuXilmassSetting = new javax.swing.JMenuItem();
        mnuKojakSetting = new javax.swing.JMenuItem();
        mnuToolsPath = new javax.swing.JMenuItem();
        mnuHelp = new javax.swing.JMenu();
        mnuAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlUserInput.setBorder(javax.swing.BorderFactory.createTitledBorder("User Inputs"));

        lblDatabasepath.setText("Database");

        lblSpectrumPath.setText("Spectrum ");

        lblOutputFolder.setText("OutPut ");

        btnDatabasePath.setText("Browse");
        btnDatabasePath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDatabasePathActionPerformed(evt);
            }
        });

        btnSpectrumPath.setText("Browse");
        btnSpectrumPath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSpectrumPathActionPerformed(evt);
            }
        });

        btnOutPutFolder.setText("Browse");
        btnOutPutFolder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOutPutFolderActionPerformed(evt);
            }
        });

        lblCrossLinker.setText("Cross-Linker");

        cmbCrossLinker.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BS3", "DSS", "EDC", "GA" }));
        cmbCrossLinker.setSelectedIndex(1);
        cmbCrossLinker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCrossLinkerActionPerformed(evt);
            }
        });

        btnAdvancedSettings.setText("Advanced Settings");
        btnAdvancedSettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdvancedSettingsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlUserInputLayout = new javax.swing.GroupLayout(pnlUserInput);
        pnlUserInput.setLayout(pnlUserInputLayout);
        pnlUserInputLayout.setHorizontalGroup(
            pnlUserInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUserInputLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlUserInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlUserInputLayout.createSequentialGroup()
                        .addGroup(pnlUserInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlUserInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblDatabasepath, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblSpectrumPath, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE))
                            .addComponent(lblOutputFolder))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlUserInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDatabasePath, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSpectrumPath, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtOutPutFolder, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlUserInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnSpectrumPath, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(btnDatabasePath, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnOutPutFolder, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlUserInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlUserInputLayout.createSequentialGroup()
                            .addComponent(lblCrossLinker)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cmbCrossLinker, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(btnAdvancedSettings, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        pnlUserInputLayout.setVerticalGroup(
            pnlUserInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUserInputLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(pnlUserInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDatabasepath, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDatabasePath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDatabasePath))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlUserInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSpectrumPath)
                    .addComponent(txtSpectrumPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSpectrumPath))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlUserInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOutputFolder)
                    .addComponent(txtOutPutFolder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOutPutFolder))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(pnlUserInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlUserInputLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(lblCrossLinker))
                    .addComponent(cmbCrossLinker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addComponent(btnAdvancedSettings))
        );

        pnlTools.setBorder(javax.swing.BorderFactory.createTitledBorder("Tools"));

        chkXilmass.setText("Xilmass");

        chkKojak.setText("Kojak");

        javax.swing.GroupLayout pnlToolsLayout = new javax.swing.GroupLayout(pnlTools);
        pnlTools.setLayout(pnlToolsLayout);
        pnlToolsLayout.setHorizontalGroup(
            pnlToolsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlToolsLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(chkXilmass, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(chkKojak)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlToolsLayout.setVerticalGroup(
            pnlToolsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlToolsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlToolsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkXilmass)
                    .addComponent(chkKojak))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnRun.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnRun.setText("Run");
        btnRun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRunActionPerformed(evt);
            }
        });

        mnuFile1.setText("File");

        mnuFile.setText("File");
        mnuFile1.add(mnuFile);

        mnuSave.setText("Save");
        mnuFile1.add(mnuSave);

        mnuExit.setText("Exit");
        mnuExit.setToolTipText("");
        mnuFile1.add(mnuExit);

        jMenuBar1.add(mnuFile1);

        mnuEdit.setText("Edit");

        mnuEditComnSetting.setText("Edit Common Setting");
        mnuEdit.add(mnuEditComnSetting);

        mnuXilmassSetting.setText("Edit Xilmass Setting");
        mnuEdit.add(mnuXilmassSetting);

        mnuKojakSetting.setText("Edit Kojak Setting");
        mnuEdit.add(mnuKojakSetting);

        mnuToolsPath.setText("Edit Tool's Path");
        mnuEdit.add(mnuToolsPath);

        jMenuBar1.add(mnuEdit);

        mnuHelp.setText("Help");

        mnuAbout.setText("About SearchGUI_XL");
        mnuHelp.add(mnuAbout);

        jMenuBar1.add(mnuHelp);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlTools, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 181, Short.MAX_VALUE)
                        .addComponent(btnRun, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnlUserInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(pnlUserInput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnRun)
                    .addComponent(pnlTools, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDatabasePathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDatabasePathActionPerformed
        
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Choose database ");
        fileChooser.setMultiSelectionEnabled(false);
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        fileChooser.setAcceptAllFileFilterUsed(false);

        int userSelection = fileChooser.showOpenDialog(null);

        if (userSelection == JFileChooser.APPROVE_OPTION) {
            String tempfile = fileChooser.getSelectedFile().getPath();
            tempfile = tempfile.replace('\\', '/');

            if (tempfile.endsWith(".fasta") || tempfile.endsWith(".FASTA") ) {
                txtDatabasePath.setText(tempfile);
            } else {
               JOptionPane.showMessageDialog(this, "database file not supported");
            }

        }
    }//GEN-LAST:event_btnDatabasePathActionPerformed

    private void btnRunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRunActionPerformed
        
        //call run method from controller
        
    }//GEN-LAST:event_btnRunActionPerformed

    private void btnAdvancedSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdvancedSettingsActionPerformed
        frmController.showAdvancedSearchParams();
        
    }//GEN-LAST:event_btnAdvancedSettingsActionPerformed

    private void btnSpectrumPathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSpectrumPathActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Choose spectral file ");
        fileChooser.setMultiSelectionEnabled(false);
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        fileChooser.setAcceptAllFileFilterUsed(false);

        int userSelection = fileChooser.showOpenDialog(null);
        if (userSelection == JFileChooser.APPROVE_OPTION) {
            String tempfile = fileChooser.getSelectedFile().getPath();
            tempfile = tempfile.replace('\\', '/');

            if (tempfile.endsWith(".mgf") || tempfile.endsWith(".mzXML")|| tempfile.endsWith(".mzML")||tempfile.endsWith(".raw")) {
                txtSpectrumPath.setText(tempfile);
            } else {
               JOptionPane.showMessageDialog(this, "spectrum file not supported");
            }
        }
    }//GEN-LAST:event_btnSpectrumPathActionPerformed

    private void btnOutPutFolderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOutPutFolderActionPerformed
         JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Choose output directory");
        fileChooser.setMultiSelectionEnabled(false);
        fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        fileChooser.setAcceptAllFileFilterUsed(false);

        int userSelection = fileChooser.showOpenDialog(null);
        if (userSelection == JFileChooser.APPROVE_OPTION) {
            String tempfile = fileChooser.getSelectedFile().getPath();
            tempfile = tempfile.replace('\\', '/');

            txtOutPutFolder.setText(tempfile);
            
        }
    }//GEN-LAST:event_btnOutPutFolderActionPerformed

    private void cmbCrossLinkerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCrossLinkerActionPerformed
        String crosslinker=cmbCrossLinker.getSelectedItem().toString();
        ConfigHolder.getInstance().setProperty("cross.linker", crosslinker);
    }//GEN-LAST:event_cmbCrossLinkerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdvancedSettings;
    private javax.swing.JButton btnDatabasePath;
    private javax.swing.JButton btnOutPutFolder;
    private javax.swing.JButton btnRun;
    private javax.swing.JButton btnSpectrumPath;
    public javax.swing.JCheckBox chkKojak;
    public javax.swing.JCheckBox chkXilmass;
    public javax.swing.JComboBox<String> cmbCrossLinker;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblCrossLinker;
    private javax.swing.JLabel lblDatabasepath;
    private javax.swing.JLabel lblOutputFolder;
    private javax.swing.JLabel lblSpectrumPath;
    private javax.swing.JMenuItem mnuAbout;
    private javax.swing.JMenu mnuEdit;
    private javax.swing.JMenuItem mnuEditComnSetting;
    private javax.swing.JMenuItem mnuExit;
    private javax.swing.JMenuItem mnuFile;
    private javax.swing.JMenu mnuFile1;
    private javax.swing.JMenu mnuHelp;
    private javax.swing.JMenuItem mnuKojakSetting;
    private javax.swing.JMenuItem mnuSave;
    private javax.swing.JMenuItem mnuToolsPath;
    private javax.swing.JMenuItem mnuXilmassSetting;
    private javax.swing.JPanel pnlTools;
    private javax.swing.JPanel pnlUserInput;
    public javax.swing.JTextField txtDatabasePath;
    public javax.swing.JTextField txtOutPutFolder;
    public javax.swing.JTextField txtSpectrumPath;
    // End of variables declaration//GEN-END:variables
}
