/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.compomics.searchgui_xl.view;

/**
 *
 * @author Genet
 */
public class Tools_Path extends javax.swing.JFrame {

    /**
     * Creates new form Tools_Path
     */
    public Tools_Path() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblxilmassPath = new javax.swing.JLabel();
        lblkojakPath = new javax.swing.JLabel();
        txtxilmassPath = new javax.swing.JTextField();
        txtKojakPathld2 = new javax.swing.JTextField();
        btnxilmassPath = new javax.swing.JButton();
        btnKojakPath = new javax.swing.JButton();
        btnApplyToolPathSetting = new javax.swing.JButton();
        btnCancelToolPathSetting = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tools Path");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Set Tools Path"));

        lblxilmassPath.setText("Xilmass");

        lblkojakPath.setText("Kojak");

        btnxilmassPath.setText("Browse");

        btnKojakPath.setText("Browse");

        btnApplyToolPathSetting.setText("Apply");

        btnCancelToolPathSetting.setText("Cancel");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblxilmassPath)
                        .addGap(18, 18, 18)
                        .addComponent(txtxilmassPath))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblkojakPath)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtKojakPathld2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnApplyToolPathSetting)
                                .addGap(32, 32, 32)
                                .addComponent(btnCancelToolPathSetting)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnKojakPath)
                    .addComponent(btnxilmassPath))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblxilmassPath)
                    .addComponent(txtxilmassPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnxilmassPath))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblkojakPath)
                    .addComponent(txtKojakPathld2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnKojakPath))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnApplyToolPathSetting)
                    .addComponent(btnCancelToolPathSetting))
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApplyToolPathSetting;
    private javax.swing.JButton btnCancelToolPathSetting;
    private javax.swing.JButton btnKojakPath;
    private javax.swing.JButton btnxilmassPath;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblkojakPath;
    private javax.swing.JLabel lblxilmassPath;
    private javax.swing.JTextField txtKojakPathld2;
    private javax.swing.JTextField txtxilmassPath;
    // End of variables declaration//GEN-END:variables
}
